<?php
// src/Entity/User.php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use FOS\UserBundle\Model\User as BaseUser;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 * @ORM\Table(name="fos_user")
 */
class User extends BaseUser
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\OneToMany(targetEntity="App\Entity\Bankcard", mappedBy="userId")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    public function __construct()
    {
        parent::__construct();
        $this->bankcards = new ArrayCollection();
        // your own logic
    }

    public function __toString()
    {
        return parent::__toString(); // TODO: Change the autogenerated stub
    }

    /**
     * Date/Time of last activity
     *
     * @var \DateTime
     *
     * @ORM\Column(name="last_activity_at", type="datetimetz", nullable=true)
     */
    protected $lastActivityAt;

    /**
     * @var string
     * @ORM\Column(name="telnr", type="string", length=255, nullable=true)
     */
    private $telnr;
    /**
     * @var string
     * @ORM\Column(name="mobilenr", type="string", length=255, nullable=true)
     */
    private $mobilenr;
    /**
     * @var string
     * @ORM\Column(name="first_name", type="string", length=255, nullable=true)
     */
    private $first_name;
    /**
     * @var string
     * @ORM\Column(name="insertion", type="string", length=255, nullable=true)
     */
    private $insertion;
    /**
     * @var string
     * @ORM\Column(name="last_name", type="string", length=255, nullable=true)
     */
    private $last_name;
    /**
     * @var string
     * @ORM\Column(name="adres", type="string", length=255, nullable=true)
     */
    private $adres;
    /**
     * @var string
     * @ORM\Column(name="zip", type="string", length=255, nullable=true)
     */
    private $zip;
    /**
     * @var string
     * @ORM\Column(name="city", type="string", length=255, nullable=true)
     */
    private $city;
    /**
     * @var string
     * @ORM\Column(name="country", type="string", length=255, nullable=true)
     */
    private $country;

//    /**
//     * @ORM\OneToMany(targetEntity="App\Entity\Bankcard", mappedBy="userId")
//     */
//    private $bankcards;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLastActivityAt(): ?\DateTimeInterface
    {
        return $this->lastActivityAt;
    }

    public function setLastActivityAt(?\DateTimeInterface $lastActivityAt): self
    {
        $this->lastActivityAt = $lastActivityAt;

        return $this;
    }

    public function getTelnr(): ?string
    {
        return $this->telnr;
    }

    public function setTelnr(?string $telnr): self
    {
        $this->telnr = $telnr;

        return $this;
    }

    public function getMobilenr(): ?string
    {
        return $this->mobilenr;
    }

    public function setMobilenr(?string $mobilenr): self
    {
        $this->mobilenr = $mobilenr;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(?string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getInsertion(): ?string
    {
        return $this->insertion;
    }

    public function setInsertion(?string $insertion): self
    {
        $this->insertion = $insertion;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(?string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getAdres(): ?string
    {
        return $this->adres;
    }

    public function setAdres(?string $adres): self
    {
        $this->adres = $adres;

        return $this;
    }

    public function getZip(): ?string
    {
        return $this->zip;
    }

    public function setZip(?string $zip): self
    {
        $this->zip = $zip;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(?string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(?string $country): self
    {
        $this->country = $country;

        return $this;
    }


//    /**
//     * @return Collection|Bankcard[]
//     */
//    public function getBankcards(): Collection
//    {
//        return $this->bankcards;
//    }
//
//    public function addBankcard(Bankcard $bankcard): self
//    {
//        if (!$this->bankcards->contains($bankcard)) {
//            $this->bankcards[] = $bankcard;
//            $bankcard->setUserId($this);
//        }
//
//        return $this;
//    }
//
//    public function removeBankcard(Bankcard $bankcard): self
//    {
//        if ($this->bankcards->contains($bankcard)) {
//            $this->bankcards->removeElement($bankcard);
//            // set the owning side to null (unless already changed)
//            if ($bankcard->getUserId() === $this) {
//                $bankcard->setUserId(null);
//            }
//        }
//
//        return $this;
//    }
}